### ISSUE TITLE
Saber a key do elemento

### ISSUE THREAD

**Issue by Th2y** [bwbr/people#73]
Para deletar (ou editar) preciso saber a key dele, porém só consigo saber o index, como o mesmo muda sempre que apaga um elemento, não dá para ser por ele.

```
deletarSkill(tabela:string){  
        this.pai = this.eu.parent();
        let index = this.pai.index().valueOf();
        this.key = index;
        this.key++;
        console.log(index)
        console.log(this.key)
        
        this.dao = ConnectionFactory
            .getConnection()
            .then((conection: any) => {
                conection.transaction([tabela], 'readwrite')
                    .objectStore(tabela)
                    .delete(this.key);                
            }).catch(erro => erro);
                            

        this.pai.remove();
    }
```

O "eu" pego pelo que recebeu clique, porém ele se refere ao html e não ao indexeddb

**Comment by josimarsts** [comment]
Thay, no trecho:

this.dao = ConnectionFactory
            .getConnection()
            .then((conection: any) => {
                conection.transaction([tabela], 'readwrite')
                    .objectStore(tabela)
                    .delete(this.key);                
            }).catch(erro => erro);
                            

        this.pai.remove();
    }

quando vc requisita a conexão, o que retorna no .delete(this.key)? Já executou algum console.log para verificar?

**Comment by Th2y** [comment]
Retorna o numero do index do elemento clicado + 1
